#+TITLE: Moonlight Xanadu
#+AUTHOR: Michal Atlas

#+EXCLUDE_TAGS: draft

#+LATEX_CLASS: book
#+LATEX_CLASS_OPTIONS: [a5paper]
#+LATEX_HEADER: \usepackage{xcolor, coelacanth, graphicx}
#+LATEX_HEADER: \pagecolor{black}
#+LATEX_HEADER: \color{white}

#+HTML_HEAD: <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/coelacanth" type="text/css"/>
#+HTML_HEAD: <style>body { font-family: 'CoelacanthRegular' } </style>

* Killing the Mansion
It is often claimed that one's life flashes before one's eyes when they
are dying. And as I sit here with all these wounds, it seems to be true,
at least partially, because I indeed am dying, but my life didn't
"flash before my very eyes", only the events of the last six hours. It
began at one of the many extravagant, some may call them quite decadent,
masked soiree. During one of many such a party, befell me a curious
encounter. Footsteps I did hear, very calculated, profoundly precise.
The type of profoundness that disturbs the mind and seizes attention.
Soon the proprietor of the disconcerting step showed herself. She
approached and introduced herself as Elisabeth maiden to the Jadewill
mansion. I retorted as is expected of me in this company. I was bid to
be a guest at yet another gala and of course, with my then lavish
manners, I accepted hastily. As soon as I did, without a second word the
maiden walked away. Disappearing in the crowd as abruptly as she had
come. At the time I thought nothing of it.

Soon I came about my old friend Clerval with whom I spent most my time,
he is a tremendously learned scholar and speaks to that accord, I bear a
strange liking to him. Angell was absorbed into this style of life with
me as the primary catalyst. Clerval bowed, I rebound with a gesture of
the hand and the greeting was over. We exchanged thoughts on the night
and Clerval inadvertently mentions Elisabeth's invitation. And so I
inquire, "Clerval, did you obey the invitation?". "No, for I fought
the invitation and overcame it."

Walking home that night, roaming around former St.~Stephen's tower, I
saw a White raven roost, its patchy skin imperceptible through its white
veil of feathers. Back home promptly after I retired to my room and bed,
I was awoken by a loud reverberation of all six walls and a pleasant
illumination coming from across the room, breaking through the blinding
darkness. Donned my gown I reach out my hand to the handle of a door
that seems to be the source of the glow. The moment my hand makes
contact with the door, I find myself before an Elizabeth stood in the
doorframe. She beckons me toward my dresser and utters that they shall
be waiting outside. Once through my front door, I enter a red and black
checkered little lounge, with a sofa in the centre and a newspaper with
a wineglass by the side. Sitting down, turning to the page with the
wineglass, I notice a drop of wine not from ink had appeared on my page.
One glance upward yielded the answer to that question, Clerval was
sitting there with a wineglass in his hand, having just spilt some. With
haste, I received an apology for the potential danger he had posed to my
suit, nevertheless interrupted by a quiet Elisabeth we were each led
back out our respective door.

We found ourselves standing in a tremendous amphitheatre headed by
several grand figures. A strikingly tall man, with great muscle, his
long silvery hair skillfully done into a wavy ponytail protruding from
his ruffled hair, and a beautifully white old shirt, decorated in red by
flowery etchings. He greets us with wide gestures, welcoming us to the
Jadewill family Mansion. Introduces himself as Astrophel, next pointing
to a pair of young girls dressed in little black dresses, whose names
are apparently Callidora and Lucilla. The latter seeming slightly off.
With the realisation that Callidora is not indeed alive, rather propped
up with strings, came a powerful sense of Astrophel's wish of silence
about the matter. You've already met Elisabeth, and Saber will show
himself in due time. We've invited you here to celebrate Callidora's
anniversary, and so we'll partake in a night of games. Each resident
having prepared something that you may play, everyone else shall watch
and enjoy themselves.

It is midnight, Let the games begin!

Lucian finds himself in a library. Not many people make up the current
inhabitants of said library. One does approach Lucian and inquires,
"Kind sir, would you mind dividing these digits into two groups?".
Lucian replies with, "I shall name them M and F.".

1F
2F
3M
4F
5F
6M
7F
8M
9M

"Correct!", exclaims the man, "and for that, I shall shoot you.".
"do not be hasty close friend", replies Lucian drawing a sword. But
haste did overpower the men, and a shot was fired. Lucian stood there
with a bullet wound in his heart, which curiously returned back from
whence it came, the damage having healed completely. A shot man dropped
the sword and proclaimed, "For now that I am dead, I shall rest my body
in this here chalk outline.", and so he did. The shooter was soon
arrested for manslaughter. Through a swift trial, with abundant
eyewitnesses, he was sentenced to solitary confinement, with
madness-alleviating torture. Lucian died in that prison at age
sixty-seven.

Lucian wakes up on a bed, in a familiar room. Green and black flower
pattern, of course, this is where he waited before the audition with
Astrophel. Checking his pocket watch, Lucian finds it is fifty-nine
minutes after midnight, and so stands up from the bed. The lodging
promptly rotates around, revealing that Clerval had been resting on the
reverse side.

Upon Clervall's awakening from his slumber, the duo is greeted by a
familiar sight, a raven had roosted upon the bedhead. It seems that
Saber had come to introduce himself. He seems to have as many bandages
as he has hairs, a long flowing red cloak hiding surely yet more ravens
and to top off the look, he had an animal skull attached to his head. He
explains that the next event will be quite simple and that their entire
purpose is to banish his pet. This is Strisk, Saber exclaimed soaring to
the ceiling and performing a backflip onto it's back.

Clervall stated in his always calm and calming voice, "RUN". We didn't
even think, running through the nearest piece of wall into a hallway
complex. We managed to evade the beast for a few years, even managing to
find some information on how we could be able to dispose of Strisk. He
could still be behind any corner, waiting\ldots{} at any time or
thought. Every time he'd catch us, the pain was less unbearable. We
tried, but one day, it came. I was on my back, Strisk devouring my body,
which instantaneously grew back and repaired. This was quite preferable
to running. The physical pain was nothing when compared to what I had
suffered through, up to that point, however, it seems that the human
psyche can only take so much pain before weakening, if only they made
that part immortal as well. But being immortal, wasn't preferable in
this situation, it was a curse, to make me able to experience what
really mattered to them. As I lay there being feasted upon, in form by
Strisk, in spirit by the rest of Jadewill, contemplating these
circumstances, a flash of light appears next to Saber riding on the back
of Strisk. The light instantaneously materialises into Callidora,
slamming with inhuman force into the side of Strisk's head, knocking off
Saber through the sheer force of impact. "I will not let you enjoy
another second of this, for what you have done Astrohpel", shouts a
very discontent Callidora at the top of her lungs. Before anyone could
even begin to contemplate the thought of beginning to consider what to
do next, reality around me started to show cracks. Through it I began to
see my room, a place I had not seen in an hour and ten minutes or over
fifty years, I have no idea. No matter how long it had taken, I was most
certainly returning there. Falling bluntly into my recliner.

It started with immense pain, my heard started bleeding. I thrashed
around for a few minutes. Then, bite marks started to show. I am glad or
sad, I don't know, I wished to die, but now I cling to life with all my
might, that is the nature of man. As I lay here with all these wounds, I
contemplate if I truly won. I would not have survived it by any chance,
but Lucilla's death shortened my suffering. Death lead to death.
However, this death, was the greatest gift.

* The Will to Tango
"So... what do we do about the book?" said Cordelia looking
around the dimly lit room, where several characters sat each in a deep
leather armchair, each of their faces illuminated by a fire shimmering
in the corner of the room. "Every one of us wants it and if one were to
take it by force, the others would quickly overwhelm him" continues
Ezekiel. A very old man, his image covered with many a grey hair and
scar, in a deep vibrant voice suggests, "Whatever would you crave in
return for surrendering it Ezekiel?". Perhaps if the person lost an arm
and a leg I might be entertained enough. Saber starts to say something
but is swiftly cut off by Ezekiel, "You are in no position to make
demands Saber, I'm not afraid to take you on, the only ones here who can
make demands except Astrophel is Callidora and Cordelia". "How about
two castles then?", says Cordelia. Callidora makes an effort to look in
the direction of Cordelia, even though her blindfold makes it a slightly
problematic task, "Truly, you would yield your claim for the low price
of two castles?". "Each", adds Cordelia. "The proposition is highly
reasonable", replies Callidora, but I must conclude this debate for the
time being for Astrophel seems to be somewhat Drowsy and I myself would
greatly benefit from a slight whiff of fresh air. Cordelia snaps at
Cordelia, "And who will guard the book if we're out?". Saber shyly and
now with a slightly startled gaze at Ezekiel, suggests "Since Callidora
has limited omnipotence she will be able to keep oversight of the book,
while I keep an eye on her". "Yep, sounds swell", exclaims Ezekiel
driving his palms right into the old carved wooden door; after the loud
collision Ezekiel left the room with Cordelia and Saber in tow.
Callidora sighs softly and beckons her butler close, whispering in his
ear "Sabien, would you mind doing something about that clock, please".
Sabien bows deeply and humbly, "Yes, ma'am". "Shall we?", asks
Clerval with hand extended towards Callidora. "Thank you, I am able to
stand by myself but walking around without colliding with all the walls
is the arduous task, safe your care for later.". And so, Clerval and
Saber walk slowly, leading Callidora through the halls towards a moonlit
corridor with a wall full of windows, all of which are now open.

Ezekiel and Cordelia may have a terrible temper, but they sure know how
to make a good draft. The walls are lined with classic wooden carvings
with depictions of torture, every stake a different carving. Some are
lined with twisted metal reinforcements shaped into giant snake
skeletons topped with animal sculptures of a cat, a winged man, a raven
and a lion. "Have you ever been here before Callidora?", Clerval
inquires. "The Jadewill Mansion's then residents never let anyone enter
other that mortals.". "However I heard that you met the family head,
what happened to them?", Clerval asked on. Callidora smirking
continues, "After Lucilla Jadewill's death, her sister massacred the
Jadewill family in retribution, not much is known about the incident.
Though without her father's centuries of wisdom, which I must say he did
not express in his manners even slightly, she could not tend to the
mansion and wasn't able to carry on her clan's legacy. The Jadewill
family was no more.". If you met him\ldots{} how old are you Callidora?
Oh that is no question to ask of a lady like myself. You are utmost
correct on that Callidora, I apologize. Callidora turns her head in the
general direction of Clerval, informing him that she wants to advise him
on a matter very important, "The Jadewill lineage is exceptionally
longer than you think and considering the mansion's history the souls it
claimed must be incomprehensible. None of us has the business of owning
such a thing.".

Saber raises his hand to stop the trio. "What might it be Saber?",
asks Clerval, "wait... ohh, what is that smell?". "This way",
signs Saber. The three run down the corridor to a half-open door. Saber
lightly nudges the door with the rear of his hand. "Keep your eyes on
the book" shouts Clerval. Callidora gently nodding. Saber catches a
glimpse of what is inside and turns around to vomit on the floor.
Callidora tenderly addresses the vomiting pile of gibbering nonsense on
the floor, "Oh we do have to do something about that weak stomach of
yours, now don't we Saber?". Clerval peers inside just to be met with
Astrophel's face. Continuing upwards with his gaze he comes to see that
his upper body is completely wrapped in spiked chains, shred absolutely
to pieces and bleeding. Clerval momentarily pauses pondering whether the
part covered in chains is the upper or lower body, considering the chain
is attached to the ceiling causing Astrophel's lifeless body to gently
sway upside down in the wind coming through the door. Ezekiel, hearing
the commotion, tears in and promptly slips on the blood.

Back in the room, now shorter by one very old man.



"So who was it Callidora?", nags Cordelia, "you know who it was...
just spill the beans so we can punish them already!".
"I will tell you in due time".
Ezekiel stands up, "If you aren't telling us them it must've been Sabien
acting on your orders, whatever she whispered when we left, must've
been the old man's death sentence".
Callidora sips a smidgen of tea and as if to herself notes,
"Oh how the young gentleman does like to cry wolf.
Scon anyone? Tea perhaps?.".

"Nevermind", rasps out Callidora sounding quite unsettled,
and looking upwards at the ceiling.
"What're you on about?", the loud boy tries to bark,
before grabbing his head in immesne pain,
and seeing the source of the pain,
attempted to lash out at it.
Just as his hand connected with a shiny cross on the ceiling,
with a flash of light, he was gone.
Yet instead of him, the center of the room had been filled,
by a four-winged being, standing about 3 feet off the floor,
with a sword in each hand, flowing white hair, and donning the name Nephilim.

Callidora, in contrast to one's expectations of her,
did not greet this stranger to her kind.
The being, very slowly extended it's hand towards the book,
after which it opened and a slip of paper was taken into Nephilim's hand.
Everybody's headaches and a collapsed Cordelia stood up as before,
when the being unexisted with yet another great flash of cross-shaped light.
Every person save for Callidora had a stunned look on
their face, one that reads "What in the nine hells just happened?".
Callidora, started calmly explaining,

"That was Nephilim, a collector of souls, for heaven's next age.
Humanity is by its nature corrupt, and when the world is beyond the control of the heathens.
They start again, anew, this world shall be the 10th hell and Eden will become the new world.
But they need the purest of souls to populate new Eden, and so they steal from us.
That right is their's to keep, for by definition, it is an act of God.",

and as the clock struck ten,
it was midnight, and on the strike of midnight, it was so.

* When Fire Reigns

Thousands of years of ancestry now lie uncovered, closer than ever,
glaring him in the eyes. Inviting the lost soul to take refuge in the
few remains of what they once bared. The burdens of all he saw seemed to
him as to shift unto his heart, with every step he grew more tired, more
scared of this world. One he had helped build, but one he did not want.
Vines surround him clutching his feet with all the might of centuries
untold as if burdens his own had not been enough to bare. He endures for
his journey's end is not far away. What he strives for, had been decades
untended to, nature's grasp had dragged its legends deep into the
ground. Stairs crumbled under every step he took, countless times he
thought he'd fall, but this he did not care for, not for a single
moment, he had not another place left to go, no other purpose. On his
journey he passed countless statues, nature had taken their faces.
Though he still recognized many, none of them could help him now. The
gateway to this sanctuary once-great now lays broken and twisted. His
mere presence disturbs this crypt lost in time. He placed his foot unto
the tiled balcony which weaved his step into a melody announcing his
arrival as it echoed through the crypt. He approaches\ldots{} gently
raising his hand, inciting the rose and vine laden door to open. The
scape of rust and degraded wood almost quelling the sounds of falling
metal echoed once again throughout the tower. He entered the room, his
feet disturbing layers of leaves, ash and dust. He had never come here,
he had never been allowed. Overhead, cowering, sat many doves, he
greeted them, for now, they shared fate. He passed torn paintings, old
carved stone and many crosses. The room had once been decorated with
beautiful wallpaper gold-laden with icons of religion and nature, even
these were now but a reminder of a bygone world. He approached an old
altar on each side of which stood the statue of an angel, one clutching
a quill and the other a piece of parchment. He approached and as he
knelt down one of the doves flew down unto the altar, raising its head
in anticipation. The old man dropped to the ground crying and begged for
forgiveness, for the world to be saved, for the world to not suffer for
his sins. He pleaded the struggle would come to an end. The dove flew
outside the tower from whence the man came and picked an olive branch,
then soared off the tower. The old man's soul was at rest, he followed
the dove outside and having completed his journey he took a step off the
ledge.

* Manifest Legacy

Standing in this hall, the air is much staler than I had expected, as my consciousness dips slightly, I remember very well... a moment.


I was leaning upon my
office door, reading the change-log of current law, looking smart, looking loyal. I
was called by the loudspeaker to my superior’s office. I scramble through the
camp as to not keep him waiting. I enter as is apt for my post, with a salute on
my chest and the words “Sir, Fjäderklädd Christopher Gosling reporting”. “At
ease”, he replied “you are no longer my problem, tommorow you are to board
the High-train, head for Daemon and report directly to the vice-secretary of the Daemon
Overseer Reignen, I don’t know why he requested your presence, however it is his will, you
will be on that train tommorow 6 hour sharp”,
he had nothing more to say to me and I had nothing more to say to him, my salute,
right arm firmly resting against my chest, I bowed low and walked out his door, dismissed I leave.

After my arrival in the tenth ward where Daemon is located,
I was directed by the automatic system to my lodgings and
allowed some 2 hours of Private Time since the journey was long and couldn’t be made within reasonable time.
And so I peered across the landscape from my balcony,
through the mist just along the horizon, Ward 11 was just about visible.
It’s exactly as I’d imagined it,
all those astonishing buildings were indeed so imposing, even more so helped by the fact that the common folk is usually kept out.
With a sip of whiskey I retire to my room.

“Good morning; Look at the sky and wake up to a day prosperous to our nation”,
they often try to change up the text, but it’s always the same crap, one starts
to internalize,
these morning drills are as despicable as the man that designed them.

I know why the Lord wants to meet with me, and when he does I shall die.
The question is how much of this I can take down with me,
the answer would come soon enough,
but I could improve my odds by finding a couple compatriots.

This group, if we may call it that, would soon come to form,
the Overseer had been called off to important duties,
this gave me a small amount of leeway to prepare.

Nobody who would be of any use to me would be allowed a stay in Daemon,
so I was forced to wander around Wards 6 or lower,
despicable places they are, everyone is forced to live in such cramped
and unsavory conditions, while the higher ups get all that space.
The founding fathers meant well, that is infallible,
lower ranking citizens simply have a higher natality,
but the high wards keep all the self-regulating statistics low.
This used to be a technocracy, but the most fit to rule,
wasn't necessarily the most fit to set his own rules.
So many years of tiny government degradation, we have to cleanse it.
Anyway, for the time being I was stuck here,
the first day, I ran into a young boy,
we ran into each other on the street,
at first I of course thought I'd been robbed, hurt or some similar.
After swiftly checking myself and seeing that he was just distracted by his camera,
I started walking away, but the boy just kept staring...
that uniform, he's from the Wrelnach,
I had little time to do background checks,
things were now or never and had to be done quite whimsically,
my least favorite way of doing things.
I retraced the few steps taken and stood close to him,
examining his stature and mannerisms.

Kommunikationschief, Izlaron division of the Wrelnach sir,
the boy exclaimed in a significantly stutterful way,
while hiding the camera behind his back.
I waved my hand dismissively, and asked him for his name.
Clerval sir. Clerval who? Clerval Angell, sir,
he continued, exhaling quite loudly,
grabbing his elbow and hanging his head, looking somewhere on my lower person.

...

At that moment, an idea struck me, and so I inquired,
do you take many photos Clerval?
Yes sir, I've been photographing everything I can,
since I got my first camera.
Have you every photographed anything illegal?
No sir, I woul... I don't like when people lie to me Clerval.
It was a stretch, I had no idea, but the bait worked,
Clerval told me about how downright passionate he was about breaking the rules with photography.
Then covered his mouth and turned around to leave, I grabbed him by the shoulder and dragged him off.
Hopefully the digital overseer would ignore his little confession,
since it would be tagged as dealt with by me.

We sifted through his photos, after a lot of time wasted calming him down and explaining I wasn't
about to bring him in.
After a couple searches we hit my jackpot, he did have photos from Aleksis Reignen's visit to his division.
And plenty enough to build a 3d copy of him, but all we needed was his face.
The software required some babysitting, so Me and Clerval stayed up late, in the end he fell asleep
in the room I rented, since it wasn't mine, I felt fine leaving him there, disconnecting the camera and taking my PDA, before leaving very early the next day.

That was one thing down, I had already taken care of another years ago.
I used to be quite close with a colleague of mine, back in the StrikeForce.
Petra Helvete was her name, she was quick and strong on her feet,
but stronger in the head, they recognized this, and made her a Mechanist
basically the moment she arrived, with additional physical training for later fieldwork.
She had closer to accessing some files, that I needed.
With her help we managed to snatch a blueprint of Reignen's prosthetic arm.
He lost his real one somewhere, and commissioned a replacement at the facility where Petra worked.
Wasn't even difficult to convince her, she was always down for no-good.

Now I had once again an old friend to visit, Petra couldn't take leave so suddenly and communicating with her,
has a risk anyway, but she didn't leave me empty-handed, apparently she has a friend who doesn't ask questions.
I walked into her establishment and somehow she recognized me, Petra probably showed her pictures or spoke about me.
Just to be safe, she still initiated the exchange, "What are you here for?".
And so I replied, "To leave something by and take something of mine",
not my idea she always thinks her catchphrases are so clever.
I put my PDA on the counter and she lifted up a very dusty clunky steel box from behind it.
I explained to her that I needed her to quickpress a Dragonfly Festival mask for me with a custom face,
she obliged and prepared the whole blank,
then I sent the extracted model I got from Clerval's photos to the press.
Once the woman saw the mask, she got stunned for more than a few moments,
then with a shaky hand took it and handed it to me.
"Is that? Is it really...", she started but I quickly replied, "I remember Petra saying you don't ask questions".
She smirked slightly but was visibly still upset.
"How much do I owe", was as far as I got before her arm shot up to my mouth, then pointed towards the door,
and she shouted, "Just get out".

Outside, I checked my PDA, and the situation on the front had resolved itself,
Overseers and the Tenno can flashport so he might be ready for me after lunch,
I've got all this sorted, so I may as well retire before the big finale.

As I had some time to kill, I walked back to the old hotel to eat,
as I was perusing the menu, who else would show up but Clerval,
from his expression, I think he slept up until moments earlier.
He ushered a Vyper deck onto the table.
I asked Clerval to choose a meal for me and he said,
"Take the third from the top, I always do, never went wrong".
So I ordered it twice and drew a hand from the deck.
He... really wasn't a good player, he mostly played light creatures, with fire spells,
because he, "enjoyed the chaos it brought to the game",
as most of this chaos comes to be when a light creature dies, yes, he saw a lot of it.
I usually play a lot of dark, which negates these effects,
but I couldn't bring myself to spoil his fun.
In the end, I let him win once, at least I managed to create a size 28 green creature,
which I would take as a personal achievemnt as this is the largest I ever managed to make one of my own cards,
but against him, it wasn't a big deal.

We ate and we laughed, well, he laughed, but I felt slightly alleviated thanks to him.
He had no idea what fate has in store for me today.
Then I stood up, payed and left.

Clerval followed me to the high-train station for some reason.
And onto the train, he didn't have the authorization to enter Daemon, I sighed and signed off on him.
A while after we crossed the border into Daemon, the dreaded message came,
there was a time and I had about an hour to use.
I walked straight into Reignen's estate, Clerval close in tail.
At the end of this corridor was a lift, he can't go in there.
Clerval is still behind me and states, "You look like a madman who's going to get himself killed".
I pay little attention to him, preparing the items I brought with me, opening the case,
and adjusting the prosthetic arm I took from the steel case, dropping it at my side.
"I ain't just meeting one lord today", I replied.
Clerval grabbed me by the shoulder and turn me around,
I used that force to drive my hand directly into the wall in-front of him,
prosthetic still adjusting some tidbits here and there.
Our faces were very close, almost touching, we both breathed heavily as if just having given a rousing speech.
I took my hand and caressed Clerval's cheek before, giving him a slow and deep kiss.
I let go when Clerval collapsed on the floor, then I turned around,
flipped Clerval's handgun in my left arm and stepped into the elevator.

Once having arrived on the correct floor, I stepped out and shot out the camera and the Overseer's vice-secretary,
the room was otherwise empty, and the camera was allowed to glitch and disconnect for a second, I would disable that measure momentarily anyway, so my job should not go interrupted.
I put on the mask and begun,
"Clearance level Overseer, surveillance footage from satellite SK451".
The machine replied, "Facial recognition scan required... Accepted".
I browsed through the footage back and forth a bit,
what I needed was a video of Aleksis authorizing a high-profile order.
I found it eventually, then swiftly extracted sound using motion amplification,
his silver decor proved quite adequate for the purpose.



A bunch of voices behind me snap me back to reality.
The hall is empty but there's probably a bunch of guards
realizing just now that they have a corpse on their hands.
But that does not concern me anymore, a few steps and I'm in Aleksis Reignen's chamber.
I walk in, and as expected see Reignen, smugly walking around, brandishing a classical sword,
used for honor duels.
His chamber is in the shape of a tall dome, with glass all across the ceiling.
I exclaim that that is not necessary, since I have already won.
He looks extremely puzzled.
I want him to understand what is happening to his oh so beloved nation as he watches it happen.
You, as the Overseer of Daemon, have a lot of power, that power is manifested in many ways,
and of course through your wide array of digital authorizations.
But a password, a face recognition scan, and an authorization key hidden in your prosthetic,
wasn't enough to stop this country's citizens from besting you.
This country was build with ideals, ideals which you and all the officials in Daemon seem to lack.
You are the ruin of my people, and that I cannot forgive.

For that purpose I issued an order in your name.
Daemon has 10s of thousands of flights both with and without passengers,
but all of them, will be heading straight for our capital, I thing some of them may even hit directly where you stand.
"That cannot be right, the Tenno will surely catch such a preposterous attempt.".
"He will, the Tenno is a powerful entity, but it would be too late, all of the aircraft's are gliding".
Every single one of those crafts has a fried circuit board, and is flying high above their recommended altitude,
with turned off engines.
Unless somebody acts really fast, Lucian shrugs, won't help much anyways, I add as the first loud explosion is heard.
Nasty things to crash these plasma engines are, aren't they Overseer?
Another explosion is heard, and yet 3 more.
Aleksis, runs down for cover and I take his place in the center of the room on a control platform.
My arms open wide looking up at the sky, at what beautiful justice I had created.
The glass shatters falling down, and raining on me and Aleksis.
The smaller fragments might've given us a chance to survive, but no chance,
the bigger shards were basically flaying us.
I stood there laughing, until my death.

* Mares of the Night :draft:
Here, I would like to try and remember some of my olden dreams.
Most of them happened a long time ago, so my memory will not serve well.
I remember voice-recording most of them, however these are lost to time so far.
When one of them comes up, I'll add its contents.
** The Plague
** The Dragon Queen
** Spaceship
** Plant Horror
** The Halls of Armour
** The Infestation

* Chronos ex Machina :draft:

#+BEGIN_QUOTE
In this story, it is quite important to understand that
none of the characters speak English unless otherwise stated.
#+END_QUOTE

Countless cracks and searing pain shoots up Einar's spine, as his back collides with a sharp rock on the ground.
The human that did throw him there laughing, above him,
tall, deceptively lean yet very strong.
A classic tale of highwayman robbery,
a few thugs ganging up on a lone traveller to the city.
For them it's like skewering fish in a barrel this time of year,
we like to have fun and
Lady Galatea's birthday celebration
is one of the biggest fairs to be hosted in our capital.
Though I probably won't get there even if they leave me alone,
since urghh... my head feels like somebody is trying to rip it away
and I don't think I feel my legs.
Some woman from the assailing party seeing my paralysing pain,
sees an opportunity to loot my belongings.
And as she was reaching over my coat I tried to defiantly defend myself arm and leg
to save my possessions.
To the surprise of me and thankfully everyone around me,
the woman's clothing vanished, having been replaced by strange black robes.
The  material was matte but strangely off,
it reflected light in ways that didn't seem natural and
blue jagged shapes became visible on her skin.

"Witch, it's a witch!", she shouted scampering back,
almost slipping before running directly in the direction of her friends.
Whom her screaming and change of visage thoroughly convinced to
spend no more time hesitating and run like hell as well.
Relieved, Einar stood up carefully

* Worldbuilding :draft:

** Chrono ex Machina
- modern civilization uses "machines" for their daily tasks
- Their authorization is based on DNA
- They work based on gestures and passwords
- Time artifact
  + Main power source
  + Takes energy from the heat death of the universe
  + causes permanent existence of the machines
    - forwards and backwards in time
- Machines have a limited range (in 100s of Km)
  + Their power falls off by distance
  + Radiation based effects
  + Plants can absorb radiation
    - Chernobyl increased radiation during fires
  + Condemned land
    - Places with constant random effects
  + Duress Point
    - center with the machine

- Examples
  + Mining machine \rightarrow Destruction school of magic
  + Entertainment \rightarrow Illusion
  + Time \rightarrow powering the other machines from the heat death, Other high-tech ("magic") artifacts are accidentally brought here
  + Medicinal \rightarrow undead
  + Transmutation
  + Divination

- Prophecies?
  - Old King's Visions
  - Vision of the operator
    - Silver ring in the sky above a mountain
    - White streaks rising from the ring as if a hurricane were passing upwards through it
    - A green dragon/spirit face rises through the ring and speaks
  - Written by hero

- Set in prohibition/victorian style backdrop
- steam vs. electricity - current wars
- Kai's fountain doesn't heal Kayden's tattoos
- Island of Iera

*** Timeline

- Crack
- The main character is bound to the time artifact
- Brings Kayden clothing from the future
  + Since he gets close enough to the artifact for the first time
- The Bandit camp thinks the Cyberpunk-like Tattoos are a plague
- Kayden goes looking for a cure
- Gets sent to Irea to Kai's fountain to heal herself and Einar (spine injury from Bandit attack)
  + By Liliana because she recognizes the tattoos (calls on them herself)
  + Kayden won't go, she thinks it's for an arrest
  + Since Einar gave Kayden future clothing he must be time-bound
  + Liliana doesn't understand the machines
  + But wants to send Einar to the Duress zone of the time-machine in an attempt to extract a prophecy
  + Einar needs to find a way to protect himself from the other effects
- Does Kayden try to steal or negotiate with Kai? (She's a bandit she'll sneak in)
  + They'll return further along in the story
- What do when he finds the artifact?
  - Releases the operator so anybody can pray to him and gain the machines' powers

** Encounters

- castle underground
- daniels ranch
- leanaras magic shop
- spire statutorium
- spire galateas chambers
- park atrium

- forest outback
- wolf cave
- basilisk lake
- saltwharf arrival
- faeria
- manor
- griffin tower

- The vampire immortal - Kai
  + Castle sitting on a Hospital machine
  + Wants to pass the mantle to someone noble

- Cities
  + Highspire
    - The Spire
    - Saltwharf
    - Cleardocks
      + Far Bank
      + Garden
      + Great Water
      + Hook
      + Middledocks
      + West District
- Seychia
  + Characters
    - Liliana (Queen)
    - Antheus (Captain of the Guard)
    - Galatea the beloved (Court Artist)
    - Ithonij (Court Geograph)
    - Richard + Daniel (Ranchmaster)
- Factions
  + The Hashtar Guild
    + Miners
  + Crimson Forsaken
  + Feyladen
    + Elves
  + Moongold Guild
  + Mornrise Kinship - Many call them druids, but those are merely disciples and students of their teachings. The Mornrise are a group that have directly bound themselves to the titan gaya.
  + Wolves of the East
    + Mercenaries

*** Characters
- Names: Shaw, Cross, Ward, Caylum, Adam Stone, Hanlock, Isaac, Gordon, Archie, Paraskeva, Titus, Sven, Joakim, Kolbjørn, Hawken, Edvin, Torstein, Magnus, Øyvind, Daniel, Anna Maria, Freya
**** Einar - Main
**** Kayden - Bandit
**** Kai - The Immortal
