#+TITLE: Moonlight Xanadu
#+AUTHOR: Michal Atlas

#+LATEX_CLASS: book
#+LATEX_CLASS_OPTIONS: [a5paper]
#+LATEX_HEADER: \usepackage{xcolor, coelacanth, graphicx}
#+LATEX_HEADER: \pagecolor{black}
#+LATEX_HEADER: \color{white}
#+LATEX_HEADER: \title{{\HUGE Moonlight Xanadu}}

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://www.pirilampo.org/styles/bigblow/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://www.pirilampo.org/styles/bigblow/css/bigblow.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://www.pirilampo.org/styles/bigblow/css/hideshow.css"/>

#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/bigblow/js/jquery-1.11.0.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/bigblow/js/jquery-ui-1.10.2.min.js"></script>

#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/bigblow/js/jquery.localscroll-min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/bigblow/js/jquery.scrollTo-1.4.3.1-min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/bigblow/js/jquery.zclip.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/bigblow/js/bigblow.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/bigblow/js/hideshow.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.min.js"></script>

* Killing the Mansion
It is often claimed that one's life flashes before one's eyes when they
are dying. And as I sit here with all these wounds, it seems to be true,
at least partially, because I indeed am dying, but my life didn't
"flash before my very eyes", only the events of the last six hours. It
began at one of the many extravagant, some may call them quite decadent,
masked soiree. During one of many such a party, befell me a curious
encounter. Footsteps I did hear, very calculated, profoundly precise.
The type of profoundness that disturbs the mind and seizes attention.
Soon the proprietor of the disconcerting step showed herself. She
approached and introduced herself as Elisabeth maiden to the Jadewill
mansion. I retorted as is expected of me in this company. I was bid to
be a guest at yet another gala and of course, with my then lavish
manners, I accepted hastily. As soon as I did, without a second word the
maiden walked away. Disappearing in the crowd as abruptly as she had
come. At the time I thought nothing of it.

Soon I came about my old friend Clerval with whom I spent most my time,
he is a tremendously learned scholar and speaks to that accord, I bear a
strange liking to him. Angell was absorbed into this style of life with
me as the primary catalyst. Clerval bowed, I rebound with a gesture of
the hand and the greeting was over. We exchanged thoughts on the night
and Clerval inadvertently mentions Elisabeth's invitation. And so I
inquire, "Clerval, did you obey the invitation?". "No, for I fought
the invitation and overcame it."

Walking home that night, roaming around former St.~Stephen's tower, I
saw a White raven roost, its patchy skin imperceptible through its white
veil of feathers. Back home promptly after I retired to my room and bed,
I was awoken by a loud reverberation of all six walls and a pleasant
illumination coming from across the room, breaking through the blinding
darkness. Donned my gown I reach out my hand to the handle of a door
that seems to be the source of the glow. The moment my hand makes
contact with the door, I find myself before an Elizabeth stood in the
doorframe. She beckons me toward my dresser and utters that they shall
be waiting outside. Once through my front door, I enter a red and black
checkered little lounge, with a sofa in the centre and a newspaper with
a wineglass by the side. Sitting down, turning to the page with the
wineglass, I notice a drop of wine not from ink had appeared on my page.
One glance upward yielded the answer to that question, Clerval was
sitting there with a wineglass in his hand, having just spilt some. With
haste, I received an apology for the potential danger he had posed to my
suit, nevertheless interrupted by a quiet Elisabeth we were each led
back out our respective door.

We found ourselves standing in a tremendous amphitheatre headed by
several grand figures. A strikingly tall man, with great muscle, his
long silvery hair skillfully done into a wavy ponytail protruding from
his ruffled hair, and a beautifully white old shirt, decorated in red by
flowery etchings. He greets us with wide gestures, welcoming us to the
Jadewill family Mansion. Introduces himself as Astrophel, next pointing
to a pair of young girls dressed in little black dresses, whose names
are apparently Callidora and Lucilla. The latter seeming slightly off.
With the realisation that Callidora is not indeed alive, rather propped
up with strings, came a powerful sense of Astrophel's wish of silence
about the matter. You've already met Elisabeth, and Saber will show
himself in due time. We've invited you here to celebrate Callidora's
anniversary, and so we'll partake in a night of games. Each resident
having prepared something that you may play, everyone else shall watch
and enjoy themselves.

It is midnight, Let the games begin!

Lucian finds himself in a library. Not many people make up the current
inhabitants of said library. One does approach Lucian and inquires,
"Kind sir, would you mind dividing these digits into two groups?".
Lucian replies with, "I shall name them M and F.".

1F
2F
3M
4F
5F
6M
7F
8M
9M

"Correct!", exclaims the man, "and for that, I shall shoot you.".
"do not be hasty close friend", replies Lucian drawing a sword. But
haste did overpower the men, and a shot was fired. Lucian stood there
with a bullet wound in his heart, which curiously returned back from
whence it came, the damage having healed completely. A shot man dropped
the sword and proclaimed, "For now that I am dead, I shall rest my body
in this here chalk outline.", and so he did. The shooter was soon
arrested for manslaughter. Through a swift trial, with abundant
eyewitnesses, he was sentenced to solitary confinement, with
madness-alleviating torture. Lucian died in that prison at age
sixty-seven.

Lucian wakes up on a bed, in a familiar room. Green and black flower
pattern, of course, this is where he waited before the audition with
Astrophel. Checking his pocket watch, Lucian finds it is fifty-nine
minutes after midnight, and so stands up from the bed. The lodging
promptly rotates around, revealing that Clerval had been resting on the
reverse side.

Upon Clervall's awakening from his slumber, the duo is greeted by a
familiar sight, a raven had roosted upon the bedhead. It seems that
Saber had come to introduce himself. He seems to have as many bandages
as he has hairs, a long flowing red cloak hiding surely yet more ravens
and to top off the look, he had an animal skull attached to his head. He
explains that the next event will be quite simple and that their entire
purpose is to banish his pet. This is Strisk, Saber exclaimed soaring to
the ceiling and performing a backflip onto it's back.

Clervall stated in his always calm and calming voice, "RUN". We didn't
even think, running through the nearest piece of wall into a hallway
complex. We managed to evade the beast for a few years, even managing to
find some information on how we could be able to dispose of Strisk. He
could still be behind any corner, waiting\ldots{} at any time or
thought. Every time he'd catch us, the pain was less unbearable. We
tried, but one day, it came. I was on my back, Strisk devouring my body,
which instantaneously grew back and repaired. This was quite preferable
to running. The physical pain was nothing when compared to what I had
suffered through, up to that point, however, it seems that the human
psyche can only take so much pain before weakening, if only they made
that part immortal as well. But being immortal, wasn't preferable in
this situation, it was a curse, to make me able to experience what
really mattered to them. As I lay there being feasted upon, in form by
Strisk, in spirit by the rest of Jadewill, contemplating these
circumstances, a flash of light appears next to Saber riding on the back
of Strisk. The light instantaneously materialises into Callidora,
slamming with inhuman force into the side of Strisk's head, knocking off
Saber through the sheer force of impact. "I will not let you enjoy
another second of this, for what you have done Astrohpel", shouts a
very discontent Callidora at the top of her lungs. Before anyone could
even begin to contemplate the thought of beginning to consider what to
do next, reality around me started to show cracks. Through it I began to
see my room, a place I had not seen in an hour and ten minutes or over
fifty years, I have no idea. No matter how long it had taken, I was most
certainly returning there. Falling bluntly into my recliner.

It started with immense pain, my heard started bleeding. I thrashed
around for a few minutes. Then, bite marks started to show. I am glad or
sad, I don't know, I wished to die, but now I cling to life with all my
might, that is the nature of man. As I lay here with all these wounds, I
contemplate if I truly won. I would not have survived it by any chance,
but Lucilla's death shortened my suffering. Death lead to death.
However, this death, was the greatest gift.

* The Will to Tango
"So... what do we do about the book?" said Cordelia looking
around the dimly lit room, where several characters sat each in a deep
leather armchair, each of their faces illuminated by a fire shimmering
in the corner of the room. "Every one of us wants it and if one were to
take it by force, the others would quickly overwhelm him" continues
Ezekiel. A very old man, his image covered with many a grey hair and
scar, in a deep vibrant voice suggests, "Whatever would you crave in
return for surrendering it Ezekiel?". Perhaps if the person lost an arm
and a leg I might be entertained enough. Saber starts to say something
but is swiftly cut off by Ezekiel, "You are in no position to make
demands Saber, I'm not afraid to take you on, the only ones here who can
make demands except Astrophel is Callidora and Cordelia". "How about
two castles then?", says Cordelia. Callidora makes an effort to look in
the direction of Cordelia, even though her blindfold makes it a slightly
problematic task, "Truly, you would yield your claim for the low price
of two castles?". "Each", adds Cordelia. "The proposition is highly
reasonable", replies Callidora, but I must conclude this debate for the
time being for Astrophel seems to be somewhat Drowsy and I myself would
greatly benefit from a slight whiff of fresh air. Cordelia snaps at
Cordelia, "And who will guard the book if we're out?". Saber shyly and
now with a slightly startled gaze at Ezekiel, suggests "Since Callidora
has limited omnipotence she will be able to keep oversight of the book,
while I keep an eye on her". "Yep, sounds swell", exclaims Ezekiel
driving his palms right into the old carved wooden door; after the loud
collision Ezekiel left the room with Cordelia and Saber in tow.
Callidora sighs softly and beckons her butler close, whispering in his
ear "Sabien, would you mind doing something about that clock, please".
Sabien bows deeply and humbly, "Yes, ma'am". "Shall we?", asks
Clerval with hand extended towards Callidora. "Thank you, I am able to
stand by myself but walking around without colliding with all the walls
is the arduous task, safe your care for later.". And so, Clerval and
Saber walk slowly, leading Callidora through the halls towards a moonlit
corridor with a wall full of windows, all of which are now open.

Ezekiel and Cordelia may have a terrible temper, but they sure know how
to make a good draft. The walls are lined with classic wooden carvings
with depictions of torture, every stake a different carving. Some are
lined with twisted metal reinforcements shaped into giant snake
skeletons topped with animal sculptures of a cat, a winged man, a raven
and a lion. "Have you ever been here before Callidora?", Clerval
inquires. "The Jadewill Mansion's then residents never let anyone enter
other that mortals.". "However I heard that you met the family head,
what happened to them?", Clerval asked on. Callidora smirking
continues, "After Lucilla Jadewill's death, her sister massacred the
Jadewill family in retribution, not much is known about the incident.
Though without her father's centuries of wisdom, which I must say he did
not express in his manners even slightly, she could not tend to the
mansion and wasn't able to carry on her clan's legacy. The Jadewill
family was no more.". If you met him\ldots{} how old are you Callidora?
Oh that is no question to ask of a lady like myself. You are utmost
correct on that Callidora, I apologize. Callidora turns her head in the
general direction of Clerval, informing him that she wants to advise him
on a matter very important, "The Jadewill lineage is exceptionally
longer than you think and considering the mansion's history the souls it
claimed must be incomprehensible. None of us has the business of owning
such a thing.".

Saber raises his hand to stop the trio. "What might it be Saber?",
asks Clerval, "wait... ohh, what is that smell?". "This way",
signs Saber. The three run down the corridor to a half-open door. Saber
lightly nudges the door with the rear of his hand. "Keep your eyes on
the book" shouts Clerval. Callidora gently nodding. Saber catches a
glimpse of what is inside and turns around to vomit on the floor.
Callidora tenderly addresses the vomiting pile of gibbering nonsense on
the floor, "Oh we do have to do something about that weak stomach of
yours, now don't we Saber?". Clerval peers inside just to be met with
Astrophel's face. Continuing upwards with his gaze he comes to see that
his upper body is completely wrapped in spiked chains, shred absolutely
to pieces and bleeding. Clerval momentarily pauses pondering whether the
part covered in chains is the upper or lower body, considering the chain
is attached to the ceiling causing Astrophel's lifeless body to gently
sway upside down in the wind coming through the door. Ezekiel, hearing
the commotion, tears in and promptly slips on the blood.

Back in the room, now shorter by one very old man.



"So who was it Callidora?", nags Cordelia, "you know who it was...
just spill the beans so we can punish them already!".
"I will tell you in due time".
Ezekiel stands up, "If you aren't telling us them it must've been Sabien
acting on your orders, whatever she whispered when we left, must've
been the old man's death sentence".
Callidora sips a smidgen of tea and as if to herself notes,
"Oh how the young gentleman does like to cry wolf.
Scon anyone? Tea perhaps?.".

"Nevermind", rasps out Callidora sounding quite unsettled,
and looking upwards at the ceiling.
"What're you on about?", the loud boy tries to bark,
before grabbing his head in immesne pain,
and seeing the source of the pain,
attempted to lash out at it.
Just as his hand connected with a shiny cross on the ceiling,
with a flash of light, he was gone.
Yet instead of him, the center of the room had been filled,
by a four-winged being, standing about 3 feet off the floor,
with a sword in each hand, flowing white hair, and donning the name Nephilim.

Callidora, in contrast to one's expectations of her,
did not greet this stranger to her kind.
The being, very slowly extended it's hand towards the book,
after which it opened and a slip of paper was taken into Nephilim's hand.
Everybody's headaches and a collapsed Cordelia stood up as before,
when the being unexisted with yet another great flash of cross-shaped light.
Every person save for Callidora had a stunned look on
their face, one that reads "What in the nine hells just happened?".
Callidora, started calmly explaining,

"That was Nephilim, a collector of souls, for heaven's next age.
Humanity is by its nature corrupt, and when the world is beyond the control of the heathens.
They start again, anew, this world shall be the 10th hell and Eden will become the new world.
But they need the purest of souls to populate new Eden, and so they steal from us.
That right is their's to keep, for by definition, it is an act of God.",

and as the clock struck ten,
it was midnight, and on the strike of midnight, it was so.

* When Fire Reigns

Thousands of years of ancestry now lie uncovered, closer than ever,
glaring him in the eyes. Inviting the lost soul to take refuge in the
few remains of what they once bared. The burdens of all he saw seemed to
him as to shift unto his heart, with every step he grew more tired, more
scared of this world. One he had helped build, but one he did not want.
Vines surround him clutching his feet with all the might of centuries
untold as if burdens his own had not been enough to bare. He endures for
his journey's end is not far away. What he strives for, had been decades
untended to, nature's grasp had dragged its legends deep into the
ground. Stairs crumbled under every step he took, countless times he
thought he'd fall, but this he did not care for, not for a single
moment, he had not another place left to go, no other purpose. On his
journey he passed countless statues, nature had taken their faces.
Though he still recognized many, none of them could help him now. The
gateway to this sanctuary once-great now lays broken and twisted. His
mere presence disturbs this crypt lost in time. He placed his foot unto
the tiled balcony which weaved his step into a melody announcing his
arrival as it echoed through the crypt. He approaches\ldots{} gently
raising his hand, inciting the rose and vine laden door to open. The
scape of rust and degraded wood almost quelling the sounds of falling
metal echoed once again throughout the tower. He entered the room, his
feet disturbing layers of leaves, ash and dust. He had never come here,
he had never been allowed. Overhead, cowering, sat many doves, he
greeted them, for now, they shared fate. He passed torn paintings, old
carved stone and many crosses. The room had once been decorated with
beautiful wallpaper gold-laden with icons of religion and nature, even
these were now but a reminder of a bygone world. He approached an old
altar on each side of which stood the statue of an angel, one clutching
a quill and the other a piece of parchment. He approached and as he
knelt down one of the doves flew down unto the altar, raising its head
in anticipation. The old man dropped to the ground crying and begged for
forgiveness, for the world to be saved, for the world to not suffer for
his sins. He pleaded the struggle would come to an end. The dove flew
outside the tower from whence the man came and picked an olive branch,
then soared off the tower. The old man's soul was at rest, he followed
the dove outside and having completed his journey he took a step off the
ledge.

* Manifest Legacy - Drafting

I was leaning upon my office door,
reading the changelog of current law,
looking smart, looking loyal.
I was called by the loudspeaker to my superior's office.
Scrumbling through the camp as to not keep him waiting.
I enter as is apt for my post, with a salute on my chest and discipline in my stride.

"Sir, Fjäderklädd Christopher Gosling reporting sir".
"At ease", replies Graham Fox.

Seems you are no longer my problem,
tommorow you are to board the High-train,
head for Daemon and report directly to the vice-secretary of the Tenno,
I don't know why he requested your presence,
however it is his will,
you will be on that train tommorow G hour sharp

Standing in this hall, the air is much staler than I had expected, as my consciousness dips slighly, I remember very well a moment. I was leaning upon my
office door, reading the changelog of current law, looking smart, looking loyal. I
was called by the loudspeaker to my superior’s office. I scrumble through the
camp as to not keep him waiting. I enter as is apt for my post, with a salute on
my chest and the words “Sir, Fjäderklädd Christopher Gosling reporting”. “At
ease”, he replied “you are no longer my problem, tommorow you are to board
the High-train, head for Daemon and report directly to the vice-secretary of the
Tenno, I don’t know why he requested your presence, however it is his will, you
will be on that train tommorow G hour sharp”, dismissed I leave.
After my arrival in the tenth ward where Daemon is located, I was directed by
the automatic system to my lodgings and allowed some 2 hours of Private Time
since, the journey was long and couldn’t be made within reasonable time. And
so I peered across the landscape from my balcony, through the mist just along
the horizon, Ward 11 was just about visible. It’s exactly as I’d imagined it, all
those astonishing buildings were indeed so imposing, even more so helped by the
fact that the common folk is usually kept out. With a sip of whisky I retire to
my room.

“Good morning; Look at the sky and wake up to a day prosperous to our nation”,
they often try to change up the text, but it’s always the same crap, one starts
to internalize

* Chronos ex Machina - Drafting

* Worldbuilding

** Manifest Legacy
- The Overseen Lands of Astartis
| Basic Info                                                      |
| ---                                                             |
| Motto: "Let the strongest guide the rest to their mutual goals" |
| Capital: Daemon                                                 |
| Anthem: Dies Irae Instrumental (Requiem in D Minor K. 626)      |
| Official Language: Asta / English (High-Classes)                |
| Government: Non-Hereditary Absolutist Technocracy               |
| Legislature: Chamber of the High Overseers + Senate             |
| Currency: Astartian Credits (Ϡ)                                 |
| Calling Code: +28                                               |

The Overseen Lands of Astartis", also known by their shortened name "Astartis", are an island nation about 1200km of the west coast of the mainland. It is ruled by an absolutistic ruler who is challenged by the chamber of the high overseers who have the right to later overrule his decisions or appeal him entirely. The state is centred heavily around the idea of testing everything and everyone rigorously, when a citizen is old enough they are subjected to an examination that determines their aptitude towards different fields and then get sent of to a school accordingly. Another unique system is the concept of wards, the citizens get ranked based on their wage and usefulness, this rank will affect permissions to travel, make certain services harder to find or completely disqualify you from buying housing in specific parts of the state, just to name a few.



- Declaratory paper of the Overseen Lands of Astartis
- Preamble
    We the founding fathers of these lands,
    the writers of this constitution
    hereby declare that all contained within this charter
    is to serve the people of the state and
    or serve the mutual benefit of us all

- State Organization
  1. Citizens are divided into Ranks 1-10
  2. These Ranks are calculated through wage and greater worth of the occupation provided by the citizen; formula provided by law
  3. Nation is divided into 14 wards
  4. Wards 1 to 10 are reserved for citizens of matching or higher Ranking
  5. Citizens are free to move to higher rank wards but will not be allowed to gain permanent residency or temporary residency for durations longer than 12 days
  6. Citizens of Rank 7 or Higher may file a request to leave the country up to three times per year for periods of up to two months total; If the quota is exceeded the citizen's property will be on lockdown for 35 days in this period there will be no access to the property and all funds and assets will be frozen. While the assets are in lockdown the original owner may request the release of property, if no request had been received in the lockdown period the state will take hold of the property.
  7. Ward 11 is reserved for executive ministers and high ranked bureaucrats
  8. Ward 12 is where intelligence bureaus and agencies have their headquarters it is never to be stationed lower than it's current location.
  9. Ward 13 is reserved for the residency and gatherings of the high council and senate.
  10. Ward 14 is the sole property and usual residence of the current Tenno.
- Governmental positions
  1. General
     1. Every governmental position has a set title and signature; not refering to them in any other way or talking ill of the post is doubting their abilities and may be considered treason; signatures not made precisely according to the diagram or in any way damaged are no longer valid
     2. Every government official excluding the Overseer Tenno must design their own crest easily distinguishable from any previous. This crest is used as the one variation to distinguish who signed any given paper
     3. Except Overseers and the Overseer Tenno the positions are selected from 60 candidates using DSOTs; the selection process of the candidates is specified by law
  2. Overseer Tenno
     1. The current Tenno may not alter the constitution in any way; he may change any law as he sees fit, this law doesn't need to be written down to be valid but in that case loses validity after 7 days, the law may be revoked by a majority of the High Overseers but at least 7 days must have passed.
     2. In the event of the death, inability to rule or other freeing of the Tenno position the new overseer will be chosen from 100 candidates using a series of DSOTs specified by law called a Conclave; The law may specify any number of DSOTs and physical or mental examinations however any tests exceeding 14 days from the beginning of the trials will not be held or if already initiated must be immediately terminated with no scoring given.
     3. In the case that the Conclave can't be held the new Tenno will be the next highest scoring surviving attendant of the last Conclave.
  3. The Council
     a. The Council consists of 5 High Overseers; all 5 of whom must be attending the council for it to utilise it's will
  4. Overseer
  5. Senator

- Acronyms

  + OAT - Occupational Aptitude Test - an examination to test your general aptitude towards a given field or set of jobs; contents specified by the examination beaureau
  + DSOT - Determining Specific Occupational Test - an examination that returns a score of how well the individual would perform in the one specific job; contents specified by the examination beareau

- Title Chart

| Name                     | Referring                                                 | Signing                                                 |
| ---                      | ---                                                       | ---                                                     |
| Overseer Tenno           | Tenno                                                     | Tenno of the Overseers                                  |
| Overseer Tenno Candidate | Adept {Regular Title}                                     | Adept {Regular Signature}                               |
| High Overseer            | High Overseer                                             | High Overseer {crest}                                   |
| Overseer                 | Sire                                                      | Overseer of Ward {ward number} {crest}                  |
| Senator                  | Senator {Surname} {number of predecessors with same name} | Senator {Crest} {number of predecessors with same name} |

- Firefly Festival - Extra day
- Vyper - Card game

- Skitora

If you ever happen to find yourself in the presence of someone of the combat domain, you may notice a small knife-like apparatus attached to their belt, often carried in sets of two, one on each side. This is called a skitora and is one of the first weapons young Astans come into contact with.

Of course, young trainees use dulled blades for the sake of their own safety. 
When unsheathed the skitora resembles what seems like a smallish circle with 3 blades protruding along the edge of the inner circle. 

A few points and an explanation of the usage:

- The user spins the centerpiece with a circular movement, setting the blades in motion.
- The centre contains an intricate set of tiny mechanisms that enable the user to shoot out or lock in place any of the 3 blades respectively.
- The blades usually feature small holes that create extremely chaotic movement while in the air, thanks to the way air moves through them.
- Contrary to popular belief, if thrown correctly the motion of the blade can indeed be predicted by the user. This, however, does nothing to help the defender as he has no way to know which configuration any particular blade has.

The skitora's widespread use emerged after common folk started to be able to evade throwing weapons, this forced researchers to find a way to adapt the throwing knife to make it harder to evade. Soon, a prototype came forth not much different from the version which we know today. It enabled the convenient usage of multiple knives at once and made the time of projection unpredictable. Today only slight improvements have been made to the Skitora and dodging it is completely out of the question.

- Animals
  + The Assistant Star

Astartis is filled to the brim with unique and fascinating creatures. Today we'll be having a look at one of the most common animals you'll find all across the island. I'm of course speaking of the Assistant star a beloved pet of many astartian citizens however also a reliable coworker and assistant, hence the name. The star gets its other name from its shape, having a multiple of 4 tentacles (4 being the most common; the record is 24, this AS had been discovered alone on a barren mountainside and is now assistant to the Tenno), protruding from a small disk-shaped body in the middle. It has no head, rather the mouth etc. is located at the bottom of the body. In the wild, they utilize their dexterity, agility and extremely sensitive sensory organ to hunt small prey. They are apt fighters, and though their tentacles are strong, the same cannot be said for their body which is extremely brittle and thus rarely exposed when fighting, severely limiting their fighting stance.

Upon closer inspection of an AS (regular abbreviation of Assistant Star) you may come to the conclusion that they are blind, never turning in any way in reaction to stimuli and don't seem to have any visible holes in the body except for the mouth, but you'd be mistaken for assuming anything close to blindness in this species. Because the circular change in texture on top of the head is actually a dome housing it's electromagnetic sensor similar to what sharks use, it is also very sensitive to vibrations and tiny amounts of ultra-violet light.

They have quite incredible regeneratory abilities in every part of the body except the exoskeleton. As a consequence scientists have been able to very easily cram the creature full of electronics like kill switches, treat dispensers, pain inducers and a computer to control those. Today you'd rarely find a tamed AS without them because they make the creature obedient and safe to use.

Statistics show that the pain-inducing apparatus is very rarely activated, probably due to the AS being an extremely simple-minded creature, it reacts to any positive stimuli well and doesn't have a need to rebel in any way.

The skin texture of the AS varies wildly from one to another, for the simple reason that in the wild they are spread all across the land from mountains to rivers to forests, some may even have fur.

*** Characters

- Lucian Christopher Gosling
  + Motivations - Career (Become Leader?) - Write a book - ?Change a law
  + See them pay (Ruse) - Planning an assassination - Traits - Laxed Morals for Goals - Alexithymia
  + Rank: Fjäderklädd at the start promoted to Vinggeneral (Wing General)
  + Identified by AI model as a danger to the crown
  + Written a book (Tanya)
  + Gain Digital Access to Aleksis Reignens Identity
    - Steps
      - Facial Recognition> Photogrammetric reconstrucion of face
      - Palm Print> from lost hand (AR has a prosthetic (Blueprint / Recovered))
      - Pass> Directional Microphone?
      - Bombers glide with idle engines through the night siently (Night Witches - bomber regiment 588)

- Clerval Angell
  + Gay
  + Photograph
  + Motivations
    - Safe world
    - Admires Lucian’s potential for power
  + Rank: Kommunikationschief (Communications Officer)

- Petra Helvete
  + Rank: Mechanist; StrikeForce

- Aleksis Reignen
  + Illusive man / Tanya style
  + Knows LCG is a spy - Wants to take him down by himself
  + Thinks too highly of his own abilities
  + Thinks assassination is the purpose
  + Rank: Monarch (Lord)
  + Wants the final word in case of betrayal,
  + systems set for him to be able to override everything

*** Setting
- Midst of conflict
- PDAs
- Style
  - Dark
  - Corridors of Law and Knowledge
  - Prison Boys??
  - WH40KRPG Style?
- Bureaucratic haven
- Calendar and Time - Use base 36 or 16 for stuff
  + Base 36 Calendars
  + Day Names
    - Standardized alternating 3 and 2 work days
      - Mun [mun]
      - Tus [tas]
      - Wed
      - Thor
      - Free
      - Fry
      - Sut
      - Sun
      - Free
  + 52 Weeks in a year
  + 4 Week Months
  + 13 Months
  + Silver Week at end of year +1 free day
  + Base 24 time
    - D hour, G hour
  + Minute and second problem Omit W and (J \rightarrow Y)
  + Zero hour
  + “A” hour = 1
  + “.” if minute or second above 59
  + No time-zones
- Neural Network AI models are trusted and used
  - Purpose of generals?
  - Implants?

*** Timeline
- Retrospective from before the Royal Chamber scene
- Reading (Law) Book
- LCG Called by Loudspeaker to superior
- Information = “LCG was promoted, thus, will travel to main city with Aleksis”
- AR plans to kill LCG himself
- Wakes up to mandated radio, shows of morning drill
- AI Identified LCG as someone who would bring down the empire
- 5 hour outage lets LCG rewrite parts of the AI
- Kabedon scene between LCG and CA right before plan
- Scene between LCG and AR in AR’s private chamber
- LCG disables all defenses and launches attack on Beaurecratic district
- AR watches his empire burn
- Why can’t anyone else have done this

- Minor Notes
  + Army Name: Wrelnach of Izlaron
  + Omniscient POV changes
  + German Sword Style (MonoWire)
  + I shall live eternally through my code
  + Every journey starts with a single step.
  + A crown does not make a king.

** Chrono ex Machina

- Space-faring humans left the planet a long time ago
  + Or they died out
- Most structures have been destroyed

- The original civilization used "machines" for their daily tasks
- Their authorization is based on DNA
- They work based on brain activity and passwords
- Examples
  + Mining machine \rightarrow Destruction school of magic
  + Entertainment \rightarrow Illusion
- Time artifact
  + Main power source
  + Takes energy from the heat death of the universe

- Many many years later a new civilization formed
  + Some DNA ended up similar, since it is the same planet with a similar environment
    - So some humans and animals are able to use the machines, which they think is magic

- Machines have a limited range (in 100s of Km)
  + Their power falls off by distance

*** Timeline

- Crack
- The main character is bound to the time artifact
- Slows time once
  + Since he gets close enough to the artifact for the first time
- Tries to find the nature of his power
- Nobody knows or wants to tell him about the nature of magic
- Tries to get audience with high kings and wizards
- What to do when he finds the artifact?

*** Encounters

- castle underground
- daniels ranch
- leanaras magic shop
- spire statutorium
- spire galateas chambers
- park atrium

- forest outback
- wolf cave
- basilisk lake
- saltwharf arrival
- faeria
- manor
- griffin tower

- The vampire immortal
  + Castle sitting on a Hospital machine
  + Found passcode

- castle underground -- "Contains a Lost Soul"

- Cities
  + Highspire
    - The Spire
    - Saltwharf
  + Cleardocks
    - Far Bank
    - Garden
    - Great Water
    - Hook
    - Middledocks
    - West District
  + Seychia
- Characters
  + Antheus (Captain of the Guard)
  + Galatea the beloved (Court Artist)
  + Ithonij (Court Geograph)
  + Richard + Daniel (Ranchmaster)
- Factions
  + The Hashtar Guild
  + Crimson Forsaken
  + Feyladen
  + Moongold Guild
  + Mornrise Kinship - Many call them druids, but those are merely disciples and students of their teachings. The Mornrise are a group that have directly bound themselves to the titan gaya.
  + Wolves of the East
