name: Build Page

on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Emacs
        uses: purcell/setup-emacs@v3.0
        with:
          version: 27.2
      
      - name: Build
        run: |
          mkdir -p build
          emacs --batch Moonlight-Xanadu.org -f 'org-html-export-to-html' -f 'org-latex-export-to-latex'
      
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: Moonlight-Xanadu.tex
          
      - name: Move to build
        run: |
          mv Moonlight-Xanadu.html build/index.html
          mv Moonlight-Xanadu.pdf build
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
